name: lazy_flutter_cli
description: >
  An interactive Next.js-style CLI tool for Flutter developers to scaffold project structures
  (Clean Architecture, MVVM) with BLoC, Riverpod, Provider, and generate feature modules instantly.
version: 1.0.0
homepage: https://github.com/YannVanneth/lazy_flutter_cli
repository: https://github.com/YannVanneth/lazy_flutter_cli

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  lazy: lazy
  lazy_cli: lazy
  lazy_flutter: lazy
  flutter_lazy: lazy
  flutter-lazy: lazy


dependencies:
  args: ^2.6.0
  mason_logger: ^0.3.5
  path: ^1.9.1
  recase: ^4.1.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.26.0

